/**
 * Converts ACF field group JSON into:
 *  1. Valid PHP registration code — acf_add_local_field_group()
 *  2. A usage snippet showing how to pull each field's value in a template
 */

function escapePhpString(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function phpValue(val, indent) {
  const pad = '    '.repeat(indent)
  const padInner = '    '.repeat(indent + 1)

  if (val === null || val === undefined) return 'null'
  if (typeof val === 'boolean') return val ? 'true' : 'false'
  if (typeof val === 'number') return String(val)
  if (typeof val === 'string') return `'${escapePhpString(val)}'`

  if (Array.isArray(val)) {
    if (val.length === 0) return 'array()'
    const items = val.map((v) => `${padInner}${phpValue(v, indent + 1)},`).join('\n')
    return `array(\n${items}\n${pad})`
  }

  if (typeof val === 'object') {
    const keys = Object.keys(val)
    if (keys.length === 0) return 'array()'
    // Preserve original keys as PHP string keys — this matters for
    // flexible_content `layouts`, which ACF keys by layout key rather
    // than storing as a plain sequential array.
    const items = keys
      .map((k) => `${padInner}'${escapePhpString(k)}' => ${phpValue(val[k], indent + 1)},`)
      .join('\n')
    return `array(\n${items}\n${pad})`
  }

  return "''"
}

export function generateFieldGroupPHP(group) {
  return `acf_add_local_field_group(${phpValue(group, 1)});`
}

/**
 * @param {string} jsonString - raw ACF JSON (single group or array of groups)
 * @returns {string} full PHP file contents
 */
export function generatePHP(jsonString) {
  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch {
    throw new Error('Invalid JSON — cannot generate PHP')
  }

  const groups = Array.isArray(parsed) ? parsed : [parsed]
  const body = groups.map((g) => generateFieldGroupPHP(g)).join('\n\n')

  return `<?php
/**
 * ACF Field Group${groups.length > 1 ? 's' : ''} — generated by ACF Field Studio
 *
 * Paste this into your theme's functions.php, or better, save it as
 * /inc/acf-fields.php and require it from functions.php:
 *
 *   require_once get_template_directory() . '/inc/acf-fields.php';
 */

if ( function_exists('acf_add_local_field_group') ) :

${body}

endif;
`
}

function fieldUsageLine(field) {
  const name  = field.name || 'field_name'
  const label = field.label || name

  switch (field.type) {
    case 'repeater':
      return `// ${label}
if ( have_rows('${name}') ) :
    while ( have_rows('${name}') ) : the_row();
        // Sub fields: ${(field.sub_fields || []).map((sf) => `get_sub_field('${sf.name}')`).join(', ') || '—'}
    endwhile;
endif;`

    case 'flexible_content': {
      const layoutsArray = field.layouts
        ? (Array.isArray(field.layouts) ? field.layouts : Object.values(field.layouts))
        : []
      const layoutCases = layoutsArray
        .map((l) => `        case '${l.name}':\n            // ${l.label || l.name} layout fields\n            break;`)
        .join('\n')
      return `// ${label}
if ( have_rows('${name}') ) :
    while ( have_rows('${name}') ) : the_row();
        switch ( get_row_layout() ) {
${layoutCases || "        // no layouts defined"}
        }
    endwhile;
endif;`
    }

    case 'group':
      return `// ${label}
$${name} = get_field('${name}');
// Sub fields: ${(field.sub_fields || []).map((sf) => `$${name}['${sf.name}']`).join(', ') || '—'}`

    case 'true_false':
      return `// ${label}
if ( get_field('${name}') ) {
    // ...
}`

    case 'image':
    case 'gallery':
      return `// ${label} — returns array by default (id/url/alt/sizes)
$${name} = get_field('${name}');`

    case 'relationship':
    case 'post_object':
      return `// ${label} — returns WP_Post object(s)
$${name} = get_field('${name}');`

    default:
      return `$${name} = get_field('${name}'); // ${label}`
  }
}

/**
 * @param {string} jsonString - raw ACF JSON (single group or array of groups)
 * @returns {string} example PHP showing how to read each top-level field
 */
export function generateUsageSnippet(jsonString) {
  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch {
    return ''
  }

  const groups = Array.isArray(parsed) ? parsed : [parsed]
  const fields = groups.flatMap((g) => g.fields || [])

  if (fields.length === 0) return '// No fields to display.'

  return fields.map(fieldUsageLine).join('\n\n')
}