/**
 * Converts ACF field group JSON into:
 *  1. Valid PHP registration code — acf_add_local_field_group()
 *  2. A usage snippet showing how to pull each field's value in a template
 */

function escapePhpString(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

function phpValue(val, indent) {
  const pad = '    '.repeat(indent)
  const padInner = '    '.repeat(indent + 1)

  if (val === null || val === undefined) return 'null'
  if (typeof val === 'boolean') return val ? 'true' : 'false'
  if (typeof val === 'number') return String(val)
  if (typeof val === 'string') return `'${escapePhpString(val)}'`

  if (Array.isArray(val)) {
    if (val.length === 0) return 'array()'
    const items = val.map((v) => `${padInner}${phpValue(v, indent + 1)},`).join('\n')
    return `array(\n${items}\n${pad})`
  }

  if (typeof val === 'object') {
    const keys = Object.keys(val)
    if (keys.length === 0) return 'array()'
    // Preserve original keys as PHP string keys — this matters for
    // flexible_content `layouts`, which ACF keys by layout key rather
    // than storing as a plain sequential array.
    const items = keys
      .map((k) => `${padInner}'${escapePhpString(k)}' => ${phpValue(val[k], indent + 1)},`)
      .join('\n')
    return `array(\n${items}\n${pad})`
  }

  return "''"
}

export function generateFieldGroupPHP(group) {
  return `acf_add_local_field_group(${phpValue(group, 1)});`
}

/**
 * @param {string} jsonString - raw ACF JSON (single group or array of groups)
 * @returns {string} full PHP file contents
 */
export function generatePHP(jsonString) {
  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch {
    throw new Error('Invalid JSON — cannot generate PHP')
  }

  const groups = Array.isArray(parsed) ? parsed : [parsed]
  const body = groups.map((g) => generateFieldGroupPHP(g)).join('\n\n')

  return `<?php
/**
 * ACF Field Group${groups.length > 1 ? 's' : ''} — generated by ACF Field Studio
 *
 * Paste this into your theme's functions.php, or better, save it as
 * /inc/acf-fields.php and require it from functions.php:
 *
 *   require_once get_template_directory() . '/inc/acf-fields.php';
 */

if ( function_exists('acf_add_local_field_group') ) :

${body}

endif;
`
}

function layoutSubFields(field) {
  if (field.type !== 'flexible_content') return null
  return field.layouts
    ? (Array.isArray(field.layouts) ? field.layouts : Object.values(field.layouts))
    : []
}

/**
 * Builds an indented "ACF sub-fields:" doc-block tree, mirroring the
 * header comment style used in hand-written block templates (nested
 * repeaters/sub-groups indented under their parent).
 */
function fieldTreeLines(fields, depth = 0) {
  const lines = []
  ;(fields || []).forEach((field) => {
    const name = field.name || 'field_name'
    const type = field.type || 'text'
    const pad = '  '.repeat(depth + 1)
    lines.push(`${pad}${name}${' '.repeat(Math.max(1, 24 - pad.length - name.length))}– ${type}`)

    if (type === 'repeater' || type === 'group') {
      lines.push(...fieldTreeLines(field.sub_fields, depth + 1))
    } else if (type === 'flexible_content') {
      ;(layoutSubFields(field) || []).forEach((l) => {
        const lpad = '  '.repeat(depth + 2)
        lines.push(`${lpad}[layout: ${l.name}]`)
        lines.push(...fieldTreeLines(l.sub_fields, depth + 2))
      })
    }
  })
  return lines
}

const IND = '    '

/**
 * Recursively renders real, nested have_rows()/the_row() usage code for a
 * list of fields — same pattern as a hand-written block template: get_field
 * at the top level, get_sub_field once inside a row loop, all the way down.
 *
 * @param {Array}  fields    - fields at this level
 * @param {number} depth     - current indent depth
 * @param {'get_field'|'get_sub_field'} accessor - how simple values are read at this depth
 */
function usageForFields(fields, depth, accessor) {
  const pad = IND.repeat(depth)

  return (fields || [])
    .map((field) => {
      const name  = field.name || 'field_name'
      const label = field.label || name

      switch (field.type) {
        case 'repeater': {
          const inner = usageForFields(field.sub_fields, depth + 2, 'get_sub_field')
          return `${pad}// ${label}
${pad}if ( have_rows('${name}') ) :
${pad}${IND}while ( have_rows('${name}') ) : the_row();

${inner || `${pad}${IND}${IND}// sub-field reads go here`}

${pad}${IND}endwhile;
${pad}endif;`
        }

        case 'flexible_content': {
          const layoutsArray = layoutSubFields(field) || []
          const layoutCases = layoutsArray
            .map((l) => {
              const layoutInner = usageForFields(l.sub_fields, depth + 4, 'get_sub_field')
              return `${pad}${IND}${IND}case '${l.name}':
${layoutInner || `${pad}${IND}${IND}${IND}// ${l.label || l.name} layout fields`}
${pad}${IND}${IND}${IND}break;`
            })
            .join('\n\n')
          return `${pad}// ${label}
${pad}if ( have_rows('${name}') ) :
${pad}${IND}while ( have_rows('${name}') ) : the_row();
${pad}${IND}${IND}switch ( get_row_layout() ) {
${layoutCases || `${pad}${IND}${IND}${IND}// no layouts defined`}
${pad}${IND}${IND}}
${pad}${IND}endwhile;
${pad}endif;`
        }

        case 'group': {
          const subs = (field.sub_fields || []).map((sf) => `$${name}['${sf.name}']`).join(', ') || '—'
          return `${pad}// ${label}
${pad}$${name} = ${accessor}('${name}');
${pad}// Sub fields: ${subs}`
        }

        case 'true_false':
          return `${pad}// ${label}
${pad}if ( ${accessor}('${name}') ) {
${pad}${IND}// ...
${pad}}`

        case 'image':
        case 'gallery':
          return `${pad}// ${label} — returns array by default (id/url/alt/sizes)
${pad}$${name} = ${accessor}('${name}');`

        case 'relationship':
        case 'post_object':
          return `${pad}// ${label} — returns WP_Post object(s)
${pad}$${name} = ${accessor}('${name}');`

        default:
          return `${pad}$${name} = ${accessor}('${name}'); // ${label}`
      }
    })
    .join('\n\n')
}

/**
 * @param {string} jsonString - raw ACF JSON (single group or array of groups)
 * @returns {string} example PHP showing how to read the fields, structured
 *                    like a real block template: a doc-block field map up
 *                    top, then nested have_rows()/the_row() usage below.
 */
export function generateUsageSnippet(jsonString) {
  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch {
    return ''
  }

  const groups = Array.isArray(parsed) ? parsed : [parsed]
  const fields = groups.flatMap((g) => g.fields || [])

  if (fields.length === 0) return '// No fields to display.'

  const title = groups[0]?.title || 'ACF Field Group'
  const treeLines = fieldTreeLines(fields)

  const header = `/**
 * ${title} — usage example
 *
 * ACF sub-fields:
${treeLines.map((l) => ` *   ${l}`).join('\n')}
 */

`

  return header + usageForFields(fields, 0, 'get_field')
}